version: "3.9"

services:
  redis:
    ports: ["6379:6379"]

  mailpit:
    ports:
      - "1025:1025"
      - "1143:1143"
      - "8025:8025"

  postgres:
    ports: ["5432:5432"]

  classifier:
    ports: ["8001:8001"]
    volumes:
      - ./classifier:/app/classifier
    command: uvicorn classifier.predict:app --host 0.0.0.0 --port 8001 --reload

  worker:
    volumes:
      - ./worker:/app/worker
      - ./decision_engine:/app/decision_engine
      - ./database:/app/database

  dashboard:
    ports: ["8080:8080"]
    volumes:
      - ./dashboard:/app/dashboard
    command: uvicorn dashboard.app:app --host 0.0.0.0 --port 8080 --reload
